---
description: Suggest updates to FreeSewing documentation or site content
labels: [ "\U0001F44D good first issue", "\U0001F4D6 documentation" ]
name: "📝 Documentation or content update"
title: "[docs]: "
body:
  - type: markdown
    attributes:
      value: "Found an issue in our documentation, a blog post, showcase or other content? Please complete the information below so we can fix it :point_down:"
  - type: input
    id: url
    attributes:
      label: "Where can we see the problem? 🤔"
      description: Provide a link here to the page to be updated. If the page provides an anchor link to the section of interest (indicated by a chain icon next to a heading) please copy that link if possible.
      placeholder: "https://freesewing/docs/patterns/aaron/cutting"
---
